development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: snitchy_beta_development

production::
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: snitchy_beta_production
